"""empty message

Revision ID: 071c815e516a
Revises: 6f26408e6d7c
Create Date: 2017-03-01 18:38:00.949902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071c815e516a'
down_revision = '6f26408e6d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('notes', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
