"""empty message

Revision ID: 40878da91325
Revises: b0336529dcce
Create Date: 2017-03-08 18:31:50.579912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40878da91325'
down_revision = 'b0336529dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'num_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('num_members', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
