"""empty message

Revision ID: 6e538d5af80b
Revises: 2c90587716d7
Create Date: 2017-02-26 21:05:10.955372

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6e538d5af80b'
down_revision = '2c90587716d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_actor_search_vector', 'actor', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('custom_list', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_custom_list_search_vector', 'custom_list', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('movie', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_movie_search_vector', 'movie', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('user', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_user_search_vector', 'user', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_search_vector', table_name='user')
    op.drop_column('user', 'search_vector')
    op.drop_index('ix_movie_search_vector', table_name='movie')
    op.drop_column('movie', 'search_vector')
    op.drop_index('ix_custom_list_search_vector', table_name='custom_list')
    op.drop_column('custom_list', 'search_vector')
    op.drop_index('ix_actor_search_vector', table_name='actor')
    op.drop_column('actor', 'search_vector')
    # ### end Alembic commands ###
