"""empty message

Revision ID: baab934ed6c7
Revises: 071c815e516a
Create Date: 2017-03-01 21:04:56.760084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baab934ed6c7'
down_revision = '071c815e516a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('recommendation_to', sa.Integer(), nullable=True))
    op.drop_constraint(u'recommendation_recommendation_id_fkey', 'recommendation', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation', 'movie', ['recommendation_to'], ['id'])
    op.drop_column('recommendation', 'recommendation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('recommendation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.create_foreign_key(u'recommendation_recommendation_id_fkey', 'recommendation', 'movie', ['recommendation_id'], ['id'])
    op.drop_column('recommendation', 'recommendation_to')
    # ### end Alembic commands ###
