"""empty message

Revision ID: cbbeafa52920
Revises: 77de0b812953
Create Date: 2017-03-11 21:33:10.318892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbeafa52920'
down_revision = '77de0b812953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('timestamp', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'timestamp')
    # ### end Alembic commands ###
